version: '3.4'

services:
  soccercrud.webapi:
    image: ${DOCKER_REGISTRY-}soccercrudwebapi
    build:
      context: .
      dockerfile: SoccerCrud.WebApi/Dockerfile
    ports:
      - "5112:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
          - sqlserver-db
  sqlserver-db:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      ports:
        - "1434:1433"
      environment:
          SA_PASSWORD: "S3cur3P@ssW0rd!"
          ACCEPT_EULA: "Y"