version: '3.4'

services:
  soccercrud.webapi:
    image: ${DOCKER_REGISTRY-}soccercrudwebapi
    build:
      context: .
      dockerfile: SoccerCrud.WebApi/Dockerfile
    ports:
      - "5112:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging