name: Multibranch

on:
  push:
    branches: 
      - *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x
    - name: Build
      run: dotnet build soccer-crud.sln --configuration Release
    - name: Test
      run: dotnet test soccer-crud.sln --configuration Release --no-build --verbosity normal